name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7m-none-eabi

      - name: rustfmt
        run: cargo fmt -- --check

      - name: clippy
        run: cargo clippy -- -D warnings
